import os
import sys

project = 'MyProject'
copyright = '2026, AutoGenerated'
author = 'AutoGenerated'

# -- General configuration ---------------------------------------------------

extensions = [
    'breathe',
    'sphinx_rtd_theme',
]

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'

# -- Breathe configuration ---------------------------------------------------

breathe_projects = {
    "MyProject": "../build/doxygen/xml"
}
breathe_default_project = "MyProject"
